steps:
  - uses: actions/checkout@v4
  - name: Build project
    run: |
      # ここにビルドコマンドを記述
  - name: Upload artifacts
    uses: actions/upload-artifact@v4
    with:
      name: my-artifact
      path: dist/
        run: npm test
